version: '3.8'

services:
  app:
    build: .
    ports:
      - "3012:3012"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=soulyaknow30
      - DB_NAME=aibroker
      - DB_PORT=5432

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: soulyaknow30
      POSTGRES_DB: aibroker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aibroker"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
